In [52]:
#1. Import the numpy package under the name np

import matplotlib.pylab as plt
import numpy as np

In [3]:
#2 numpy version & numpy configuration

print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/user/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

In [4]:
#3 1D array of zeros of size 10

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4 Memory size of the array

Z = np.zeros((32,12))
print("%d bytes" % (Z.size * Z.itemsize))

3072 bytes


In [6]:
#5 1D array with values ranging from 10 to 58

Z = np.arange(10,59)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


In [11]:
#6 Reverse the order of the values

a = np.arange(10)
print("Original Array: ")
print(a)
print("Reverse  Array")
a = a[::-1]
print(a)


Original Array: 
[0 1 2 3 4 5 6 7 8 9]
Reverse  Array
[9 8 7 6 5 4 3 2 1 0]


In [12]:
#7 3x3 matrix with values ranging from 0 to 8

a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#8 3x3 identity matrix

a = np.identity(3)
print('3*3 matrix:')
print(a)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#9 Find and print the maximum values

Z = np.random.random((10,11))
Zmax = Z.max()
print(Zmax)

0.9867177227013264


In [17]:
#10 7*7 array with 1s on the borders and 0s everywhere else

a = np.ones((7,7))

print("Original Array: ")
print(a)
print(" 1 on the border & 0 everywhere else: ")
a[1:-1,1:-1] = 0
print(a)


Original Array: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
 1 on the border & 0 everywhere else: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [21]:
#11 Pad the existing array below with zeros using the NumPy pad function

Z = np.ones((5,5))
Z = np.pad(Z, pad_width = 1, mode = 'constant', constant_values = 0)
print(Z)
Z[:,[0,-1]] = 0
Z[[0,-1],:] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [23]:
#12 Extract the integer part of the random array

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[2. 3. 4. 4. 8. 6. 1. 4. 8. 4.]
[2. 3. 4. 4. 8. 6. 1. 4. 8. 4.]
[2. 3. 4. 4. 8. 6. 1. 4. 8. 4.]
[2 3 4 4 8 6 1 4 8 4]
[2. 3. 4. 4. 8. 6. 1. 4. 8. 4.]


In [24]:
#13 5x5 matrix with rows with equal values ranging from 0 to 4

Z = np.zeros((5,5))
Z += np.arange(5)

print(Z)

#without broadcasting

Z = np.tile(np.arange(0,5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [25]:
#14 Vector of size 10 with values ranging from 0 to 1

Z = np.linspace(0,1,11,endpoint=True)[1:-1]
print(Z)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [26]:
#15 Random vector of size 10 and sort it

Z = np.random.random(10)

print("Original array:")
print(Z)

Z.sort()

print("Sorted array:")
print(Z)

Original array:
[0.43719283 0.6050043  0.78752859 0.86897036 0.26708595 0.61117844
 0.69857727 0.4704286  0.30844283 0.9500929 ]
Sorted array:
[0.26708595 0.30844283 0.43719283 0.4704286  0.6050043  0.61117844
 0.69857727 0.78752859 0.86897036 0.9500929 ]


In [28]:
#16 Consider the cartesian coordinates below (X and Y), convert them to polarcoordinates (R and T)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

[0.92831943 0.34736562 0.71339117 0.85873576 0.80569694 0.71764314
 0.47958218 0.90361289 0.99636369 0.88749218]
[1.09804701 1.01748166 0.9024424  0.45575241 0.18542776 1.50154009
 0.82485268 0.00881976 1.33692301 0.52721461]


In [29]:
#17 Create random vector of size 10 and replace the maximum value by 0

Z = np.random.random(10)

print("Original array:")
print(Z)

Z[Z.argmax()] = 0

print("Maximum value replaced by 0:")
print(Z)

Original array:
[0.52378776 0.65031678 0.07534404 0.66140668 0.13614924 0.19872297
 0.48009552 0.86310549 0.60796629 0.85633215]
Maximum value replaced by 0:
[0.52378776 0.65031678 0.07534404 0.66140668 0.13614924 0.19872297
 0.48009552 0.         0.60796629 0.85633215]


In [30]:
#18 Find the nearest value from a given value (z) in an array (Z)

Z = np.random.uniform(0, 1, 10)
z = 0.5
S = Z.flat[np.abs(Z - z).argmin()]
print(S)

0.5234349722240245


In [31]:
#19 Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutivezeros interleaved between each value?

Z = np.array([5, 4, 3, 2, 1])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[5. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1.]


In [43]:
#20 Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
              
print(A * B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [42]:
#21 Swap the first and second rows of the 2D array below

W = np.arange(30).reshape(6,5)
print(W)
print()

W[[0,1]] = W[[1,0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [62]:
#22 Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box that encloses all non-zero elements in the input array

from PIL import Image
import numpy as np

def bbox(img):
    img = np.where(img != 0)
    rows = np.any(img, axis=1)
    cols = np.any(img, axis=0)
    r1, r2 = np.where(rows)[0][[0, -1]]
    c1, c2 = np.where(cols)[0][[0, -1]]
    return (r1,c1),(r2,c2)

img = np.array(Image.open('bin_image.png').convert('L'))

bbox(img)


FileNotFoundError: [Errno 2] No such file or directory: 'bin_image.png'

In [63]:
#23 Write a function to compute the average over a sliding window of length N over a 1D array?

def moving_average(x,N = 3):
    ret = np.cumsum(x, dtype = float)
    ret[N:] = ret[N:]-ret[:-N]
    return ret[N-1:]/N

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]


In [64]:
#24 Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(C)


[0 2 1 1 2 0 1]


In [66]:
#25 Find the most frequent value in the array below?

Z = np.random.randint(0,10,50)

print("Original Array: ")
print(Z)
print("Most frequent value: ")
print(np.bincount(Z).argmax())

Original Array: 
[9 1 4 0 7 2 8 7 2 3 7 7 9 6 5 1 2 2 6 1 9 2 0 1 9 4 5 4 7 4 0 9 6 0 7 7 5
 1 6 0 9 3 3 6 5 0 4 3 5 5]
Most frequent value: 
7


In [69]:
#26 Write a function to return the n largest values of an array

def nlargest(a,n = 5):
    srtarr = np.argsort(a)
    sorted_arr = a[srtarr]
    result = sorted_arr[-n:]
    return result[0]

Z = np.arange(10000)
np.random.shuffle(Z)

n = 5
print(nlargest(Z,n))

9995
